### PR TITLE
[PA128] News controller and api

### PR DESCRIPTION
**Pull request by nicolelst**
https://aura-cz2006.atlassian.net/browse/PA-128?atlOrigin=eyJpIjoiOTY2YTZjOTk2YzU3NGZiNGE3NjJmMWE5OTIzMDRkZTEiLCJwIjoiaiJ9

done, but yet to be tested with new backend api
need to check that parsing of json in api handler is consistent with backend design

### CODE REVIEW

**Comment by nicolelst** [comment]
still missing lat and long for location

**Comment by nicolelst** [comment]
> still missing lat and long for location

added in last commit

**Comment by nicolelst** [comment]
ISSUE: FAB in news is missing

**Review by celerie — APPROVED** [review]
lgtm

**Pull request merged**
