### PR TITLE
[PA-35] Added detailed thread view

### PR DESCRIPTION
**Pull request by nicolelst**
this is half of PA-35. detailed meetup view is yet to be implemented https://aura-cz2006.atlassian.net/browse/PA-35?atlOrigin=eyJpIjoiNzkwODc4OTRkMjk2NGU0ZTlkZmZmNGU4OTNkZjIyZTAiLCJwIjoiaiJ9

completed detailed view for discussion threads:
- display full text of thread
- display all comments
- functional comment input field 

Not part of this PR: PA-47
- assign unique ID to new comment
- validate comments for censored text

### CODE REVIEW

**Comment by nicolelst** [comment]
@RealDyllon please help to remove the tester function in `main` and change `return MaterialApp` to `return Scaffold` when merging. thanks!

**Comment by nicolelst** [comment]
@RealDyllon this branch has been absorbed by community_fab_editLocation. I debugged the like button there (thread now stores/removes user that tapped liked button) but this change is not noticeable from front-end in the simple test provided.

**Comment by RealDyllon** [comment]
@nicolelst could you add the like button fix to this branch as well?

**Comment by nicolelst** [comment]
@RealDyllon like button has been debugged.

**Pull request merged**
