### PR TITLE
Added  OSM map layer for map tab

### PR DESCRIPTION
**Pull request by nicolelst**
https://aura-cz2006.atlassian.net/browse/PA-38?atlOrigin=eyJpIjoiN2EyZmJmMDRkZjAzNDFhZGE1ODM4MzMwMGUyZDg0MzgiLCJwIjoiaiJ9

TODO:
- attribution not locked in place, disappears after rotation (flutter_map + leaflet bug)

### CODE REVIEW

**Comment by RealDyllon** [comment]
@nicolelst should this PR be marked as draft for the time being, or is it ready for review?

**Comment by nicolelst** [comment]
> @nicolelst should this PR be marked as draft for the time being, or is it ready for review?

@RealDyllon the task was to create a map layer as the base for the map tab. iinw, @fath3725 is already working based on this branch. 
do we have plans to switch from OSM to mapbox?

**Comment by RealDyllon** [comment]
@nicolelst let's switch to mapbox in the next sprint. Therefore let's just flutter_map for the skeleton, and mapbox for the final app.

**Comment by RealDyllon** [comment]
> attribution not locked in place, disappears after rotation (flutter_map + leaflet bug)

For this issue, let's just ignore it for now, since we'll be switching to mapbox_gl

**Comment by RealDyllon** [comment]
@nicolelst could you replace the latlong library with another newer lib?

**Comment by nicolelst** [comment]
@RealDyllon latlong has been replaced by [latlong2](https://pub.dev/packages/latlong2).

**Pull request merged**
